dependencies:
  - name: inventory-management-service-jmt
    version: 1.0.0-2
    repository: http://artifactory.mooc-one-ocp-clus-532507-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/mooc-team-one/
